language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tylersuchan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tylersuchan/docker-react npm run test